### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by Shenfeichen** [AKSW/LIMES#15]
I downloaded LIMESRC0.6.RC3.2.zip and run the command "java -jar LIMES.jar Release_Examples/dbpedia-drugbank.xml". I got the following error message: 

 INFO [main] (PPJoinController.java:131) - ID: dbpedia
Var: ?x
Prefixes: {dc=http://purl.org/dc/terms/, dbpedia-p=http://dbpedia.org/property/, diseasome=http://www4.wiwiss.fu-berlin.de/diseasome/resource/diseasome/, rdfs=http://www.w3.org/2000/01/rdf-schema#, drugbank=http://www4.wiwiss.fu-berlin.de/drugbank/resource/drugbank/, foaf=http://xmlns.com/foaf/0.1/, dbpedia=http://dbpedia.org/ontology/, sider=http://www4.wiwiss.fu-berlin.de/sider/resource/sider/, owl=http://www.w3.org/2002/07/owl#, rdf=http://www.w3.org/1999/02/22-rdf-syntax-ns#}
Endpoint: http://dbpedia.org/sparql
Graph: null
Restrictions: [?x rdf:type dbpedia:Drug]
Properties: [rdfs:label]
Functions: {rdfs:label={rdfs:label=nolang->lowercase}}
Page size: 1000
Type: sparql

 INFO [main] (PPJoinController.java:132) - ID: drugbank
Var: ?y
Prefixes: {dc=http://purl.org/dc/terms/, dbpedia-p=http://dbpedia.org/property/, diseasome=http://www4.wiwiss.fu-berlin.de/diseasome/resource/diseasome/, rdfs=http://www.w3.org/2000/01/rdf-schema#, drugbank=http://www4.wiwiss.fu-berlin.de/drugbank/resource/drugbank/, foaf=http://xmlns.com/foaf/0.1/, dbpedia=http://dbpedia.org/ontology/, sider=http://www4.wiwiss.fu-berlin.de/sider/resource/sider/, owl=http://www.w3.org/2002/07/owl#, rdf=http://www.w3.org/1999/02/22-rdf-syntax-ns#}
Endpoint: http://www4.wiwiss.fu-berlin.de/drugbank/sparql
Graph:
Restrictions: [?y rdf:type drugbank:drugs]
Properties: [rdfs:label, drugbank:genericName]
Functions: {rdfs:label={name=nolang->lowercase}, drugbank:genericName={name=nolang->lowercase}}
Page size: 1000
Type: sparql

 INFO [main] (PPJoinController.java:137) - Loading source data ...
 INFO [main] (HybridCache.java:245) - No cached data found for dbpedia
 INFO [main] (QueryModuleFactory.java:19) - Generating <sparql> reader
 INFO [main] (SparqlQueryModule.java:93) - Properties are [rdfs:label]
 INFO [main] (SparqlQueryModule.java:135) - Query issued is
PREFIX dc: <http://purl.org/dc/terms/>
PREFIX dbpedia-p: <http://dbpedia.org/property/>
PREFIX diseasome: <http://www4.wiwiss.fu-berlin.de/diseasome/resource/diseasome/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX drugbank: <http://www4.wiwiss.fu-berlin.de/drugbank/resource/drugbank/>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX dbpedia: <http://dbpedia.org/ontology/>
PREFIX sider: <http://www4.wiwiss.fu-berlin.de/sider/resource/sider/>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
SELECT DISTINCT ?x ?v0
WHERE {
?x rdf:type dbpedia:Drug .
?x rdfs:label ?v0 .
}
 INFO [main] (SparqlQueryModule.java:137) - Querying the endpoint.
 INFO [main] (SparqlQueryModule.java:145) - Getting statements 0 to 1000
Exception in thread "main" HttpException: HttpException: 502 Bad Gateway: HttpException: 502 Bad Gateway
	at com.hp.hpl.jena.sparql.engine.http.HttpQuery.execCommon(HttpQuery.java:340)
	at com.hp.hpl.jena.sparql.engine.http.HttpQuery.execGet(HttpQuery.java:190)
	at com.hp.hpl.jena.sparql.engine.http.HttpQuery.exec(HttpQuery.java:147)
	at com.hp.hpl.jena.sparql.engine.http.QueryEngineHTTP.execSelect(QueryEngineHTTP.java:117)
	at de.uni_leipzig.simba.query.SparqlQueryModule.fillCache(SparqlQueryModule.java:171)
	at de.uni_leipzig.simba.query.SparqlQueryModule.fillCache(SparqlQueryModule.java:38)
	at de.uni_leipzig.simba.cache.HybridCache.getData(HybridCache.java:247)
	at de.uni_leipzig.simba.cache.HybridCache.getData(HybridCache.java:218)
	at de.uni_leipzig.simba.controller.PPJoinController.run(PPJoinController.java:139)
	at de.uni_leipzig.simba.controller.PPJoinController.main(PPJoinController.java:32)
Caused by: HttpException: 502 Bad Gateway
	at com.hp.hpl.jena.sparql.engine.http.HttpQuery.execCommon(HttpQuery.java:301)

Just wondering what is the reason to cause 502 Bad Gateway exception ?

Thanks

**Comment by ngonga** [comment]
It's simply due to the endpoint being down. Sorry, not much we can do about that. Please try changing the endpoint to the Drugbank endpoint of the Uni Mannheim. If the DBpedia  query failed, then simply try again :)
