### ISSUE TITLE
Does LIMES support this?

### ISSUE THREAD

**Issue by umasirci** [AKSW/LIMES#17]
For my master thesis in Uni-Bonn,  I am using LIMES to interlink OpenAIRE dataset (which is a dataset containig scholarly metadata) to DBLP.
We are facing a problem that I want to ask you.
In our dataset ,we have data about publications so does DBLP. 
Using LIMES, I am able to find match those properties of publications which are literal in both datasets for example title but for authors  which are resources I could not find how LIMES does it.
It seems in each interlinking rule, one can define only one VAR and below it is only possible to take the properties under that VAR. 
In metric part, I want to compare publication names and author names. I can access publication names but I can’t access author names in metric part.( Because, authors are resources and not a literal.) Is there a way to do this in LIMES?

**Comment by ngonga** [comment]
Not sure I understand your request. Authors should have a label. Please simply use a path query to get the authors' names, e.g., AND(trigrams(x.name, y.name)|0.9, trigrams(x/author.name, y/author.name)|0.9). Please check the manual and the SPARQL specification for details on path queries.
