### ISSUE TITLE
Returned 0 links to review

### ISSUE THREAD

**Issue by FatemeSH** [AKSW/LIMES#20]
Hi
this is my code for finding links between similar keywords in my own database
the problem is that, it returns no links
I think the code could not read the sh5.nt. is it right?
can you help me?

this is my code:
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE LIMES SYSTEM "limes.dtd">
<LIMES>
	<PREFIX>
		<NAMESPACE>http://www.w3.org/1999/02/22-rdf-syntax-ns#</NAMESPACE>
		<LABEL>rdf</LABEL>
	</PREFIX>
		<PREFIX>
		<NAMESPACE>http://ltsc.ieee.org/rdf/lomv1p0/lom#</NAMESPACE>
		<LABEL>lom</LABEL>
	</PREFIX>
	<PREFIX>
		<NAMESPACE>http://www.w3.org/2000/01/rdf-schema#</NAMESPACE>
		<LABEL>rdfs</LABEL>
	</PREFIX>
	<PREFIX>
		<NAMESPACE>http://xmlns.com/foaf/0.1/</NAMESPACE>
		<LABEL>foaf</LABEL>
	</PREFIX>
	<PREFIX>
		<NAMESPACE>http://www.w3.org/2002/07/owl#</NAMESPACE>
		<LABEL>owl</LABEL>
	</PREFIX>
	<PREFIX>
		<NAMESPACE>http://localhost:2020/resource/vocab/</NAMESPACE>
		<LABEL>vocab</LABEL>
	</PREFIX>

	<SOURCE>
		<ID>mydb1</ID>
		<ENDPOINT>C:/Users/Fateme/Desktop/sh5.nt</ENDPOINT>
		<VAR>?x</VAR>
		<PAGESIZE>1000</PAGESIZE>
		<RESTRICTION>?x rdf:type vocab:sh5</RESTRICTION>
		<PROPERTY>lom:keyword</PROPERTY>
		<TYPE>NT</TYPE>
	</SOURCE>
	<TARGET>
		<ID>mydb2</ID>
		<ENDPOINT>C:/Users/Fateme/Desktop/sh5.nt</ENDPOINT>
		<VAR>?y</VAR>
		<PAGESIZE>1000</PAGESIZE>
		<RESTRICTION>?y rdf:type vocab:sh5</RESTRICTION>
		<PROPERTY>lom:keyword</PROPERTY>
		<TYPE>NT</TYPE>
	</TARGET>
	<METRIC>
	trigrams(x.lom:keyword,y.lom:keyword)
	</METRIC>
	<ACCEPTANCE>
		<THRESHOLD>0.1</THRESHOLD>
		<FILE>first.nt</FILE>
		<RELATION>owl:sameAs</RELATION>
	</ACCEPTANCE>
	<REVIEW>
		<THRESHOLD>0.1</THRESHOLD>
		<FILE>first_reviewme.nt</FILE>
		<RELATION>owl:sameAs</RELATION>
	</REVIEW>
	<EXECUTION>Simple</EXECUTION>
	<OUTPUT>NT</OUTPUT>
</LIMES>

thanks

**Comment by ngonga** [comment]
Review threshold = accept threshold means LIMES will accept all links 
with trigrams >= 0.1 and not return any links to review, asthere are no 
numbers in the interval ]0.1, 0.1]. Please check your accept file.

> this is my code for finding links between similar keywords in my own 
> database

-- 
Axel Ngonga, Dr. rer. nat
Head of AKSW
Augustusplatz 10
Room P905
04109 Leipzig
http://aksw.org/AxelNgonga

Tel: +49 (0)341 9732341
Fax: +49 (0)341 9732239

**Comment by FatemeSH** [comment]
my accept file and review file have no links.in attach file output is shown(In my database threre are many similariters in keyword) Fateme Shahrabi Farahani,
B.S. Student in Information Technology Engineering,
Department of Electrical and Computer Engineering,
College of Engineering,
University of Tehran,
Tehran, Iran. 

    On Monday, July 25, 2016 11:47 PM, Axel Ngonga <notifications@github.com> wrote:
 

 Review threshold = accept threshold means LIMES will accept all links 
with trigrams >= 0.1 and not return any links to review, asthere are no 
numbers in the interval ]0.1, 0.1]. Please check your accept file.

> this is my code for finding links between similar keywords in my own 
> database

-- 
Axel Ngonga, Dr. rer. nat
Head of AKSW
Augustusplatz 10
Room P905
04109 Leipzig
http://aksw.org/AxelNgonga

Tel: +49 (0)341 9732341
Fax: +49 (0)341 9732239

**Comment by FatemeSH** [comment]
I tested with this endpoint
http://localhost:2020/snorql/
but I got this error: StAX error:skipToHead:Unexpected tag:<http://www.w3.org/1999/xhtml>html
would you please help me?
 this my code:
	<SOURCE>
		<ID>mydb1</ID>
		<ENDPOINT>http://localhost:2020/snorql/</ENDPOINT>
		<VAR>?x</VAR>
		<PAGESIZE>1000</PAGESIZE>
		<RESTRICTION>?x rdf:type vocab:sh5.</RESTRICTION>
		<PROPERTY>lom:keyword</PROPERTY>
	</SOURCE>
	<TARGET>
		<ID>mydb2</ID>
		<ENDPOINT>http://localhost:2020/snorql/</ENDPOINT>
		<VAR>?y</VAR>
		<PAGESIZE>1000</PAGESIZE>
		<RESTRICTION>?y rdf:type vocab:sh5.</RESTRICTION>
		<PROPERTY>lom:keyword</PROPERTY>
	</TARGET>
	<METRIC>
	trigrams(x.lom:keyword,y.lom:keyword)
	</METRIC>
	<ACCEPTANCE>
		<THRESHOLD>0.95</THRESHOLD>
		<FILE>first.nt</FILE>
		<RELATION>owl:sameAs</RELATION>
	</ACCEPTANCE>
	<REVIEW>
		<THRESHOLD>0.9</THRESHOLD>
		<FILE>first_reviewme.nt</FILE>
		<RELATION>owl:sameAs</RELATION>
	</REVIEW>
	<EXECUTION>Simple</EXECUTION>
	<OUTPUT>NT</OUTPUT>
</LIMES>

thanks for your help

**Comment by FatemeSH** [comment]
this is my code:
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE LIMES SYSTEM "limes.dtd">
<LIMES>
	<PREFIX>
		<NAMESPACE>http://www.w3.org/1999/02/22-rdf-syntax-ns#</NAMESPACE>
		<LABEL>rdf</LABEL>
	</PREFIX>
		<PREFIX>
		<NAMESPACE>http://ltsc.ieee.org/rdf/lomv1p0/lom#</NAMESPACE>
		<LABEL>lom</LABEL>
	</PREFIX>
	<PREFIX>
		<NAMESPACE>http://www.w3.org/2000/01/rdf-schema#</NAMESPACE>
		<LABEL>rdfs</LABEL>
	</PREFIX>
	<PREFIX>
		<NAMESPACE>http://xmlns.com/foaf/0.1/</NAMESPACE>
		<LABEL>foaf</LABEL>
	</PREFIX>
	<PREFIX>
		<NAMESPACE>http://www.w3.org/2002/07/owl#</NAMESPACE>
		<LABEL>owl</LABEL>
	</PREFIX>
	<PREFIX>
		<NAMESPACE>http://localhost:2020/resource/vocab/</NAMESPACE>
		<LABEL>vocab</LABEL>
	</PREFIX>

	<SOURCE>
		<ID>mydb1</ID>
		<ENDPOINT>http://localhost:2020/snorql/</ENDPOINT>
		<VAR>?x</VAR>
		<PAGESIZE>1000</PAGESIZE>
		<RESTRICTION>?x rdf:type vocab:sh5.</RESTRICTION>
		<PROPERTY>lom:keyword</PROPERTY>
	</SOURCE>
	<TARGET>
		<ID>mydb2</ID>
		<ENDPOINT>http://localhost:2020/snorql/</ENDPOINT>
		<VAR>?y</VAR>
		<PAGESIZE>1000</PAGESIZE>
		<RESTRICTION>?y rdf:type vocab:sh5.</RESTRICTION>
		<PROPERTY>lom:keyword</PROPERTY>
	</TARGET>
	<METRIC>
	trigrams(x.lom:keyword,y.lom:keyword)
	</METRIC>
	<ACCEPTANCE>
		<THRESHOLD>0.95</THRESHOLD>
		<FILE>first.nt</FILE>
		<RELATION>owl:sameAs</RELATION>
	</ACCEPTANCE>
	<REVIEW>
		<THRESHOLD>0.9</THRESHOLD>
		<FILE>first_reviewme.nt</FILE>
		<RELATION>owl:sameAs</RELATION>
	</REVIEW>
	<EXECUTION>Simple</EXECUTION>
	<OUTPUT>NT</OUTPUT>
</LIMES>

**Comment by FatemeSH** [comment]
I solved my problem
the problem is because of snorql
in LIMES config file we should write sparql
with this endpoint works:
<ENDPOINT>http://localhost:2020/sparql</ENDPOINT>
