### ISSUE TITLE
Limes Issue

### ISSUE THREAD

**Issue by 90arslan** [AKSW/LIMES#27]
Hello Everyone,
I am trying to interlink openaire and Cordis datasets by using their endpoints. but these data sets have very large data. when i interlink them I faced "Out of memory error". So How i can tackle this problem.
How i can put limit on limes config file if i just want to take only 1000 lines of data.

![screenshot from 2018-05-20 12-04-44](https://user-images.githubusercontent.com/16212744/40349127-e3f3af40-5da5-11e8-8306-4f2f3ba638bc.png)

**Comment by Kleanthi** [comment]
Hello!
First of all, please use the new LIMES, available at: https://github.com/dice-group/LIMES.
We have an updated user manual where  you can find the answer to your question.
Just set the PAGESIZE tag at your requested size of triples if you are querying endpoints. Otherwise, if you are using a file, the PAGESIZE tag is set to -1, cause LIMES will retrieve all the triples of the file.

**Comment by 90arslan** [comment]
I set the page size like 1000 then it reads data 0 to 1000, 1000 to 2000 and continue...

**Comment by Kleanthi** [comment]
As you can read in the manual, the PAGESIZE is set to a value different from -1 when querying endpoints. Otherwise LIMES will retrieve all the triples of the file in batches of e.g. 1000 triples. 
I suggest that you either query the endpoints via LIMES using the configuration file and setting the PAGESIZE tag to 1000 or use data sets file with only 1000 triples.

**Comment by 90arslan** [comment]
ok thankyou :+1:

**Comment by 90arslan** [comment]
Hi once again,

@Kleanthi I have a question. I am trying to interlink Cordis Endpoint with openaire endpoint. my resulting dataset have some values that are not same. how i can get  exact same data from both data sets.

**Comment by Kleanthi** [comment]
From what I understand, you want to pre-process your datasets in a way. 
If that is the case, this is beyond scope of LIMES.

**Comment by 90arslan** [comment]
<SOURCE>
        <ID>openaire</ID>
        <ENDPOINT>http://lod.openaire.eu/sparql/</ENDPOINT>
        <VAR>?x</VAR>
        <PAGESIZE>100</PAGESIZE>
		<MAXOFFSET>2000</MAXOFFSET>
        <RESTRICTION>?x a oav:OrganizationEntity</RESTRICTION>
        <PROPERTY>oav:prefLabel AS cleaniri RENAME name</PROPERTY>
    </SOURCE>
	
	
	
    <TARGET>
	<ID>cordis</ID>
	<ENDPOINT>http://cordis.rkbexplorer.com/sparql/</ENDPOINT>
	<VAR>?y</VAR>
	<PAGESIZE>100</PAGESIZE>
	<MAXOFFSET>2000</MAXOFFSET>
	<RESTRICTION>?y a akt:Organization</RESTRICTION>
	
	<PROPERTY>rdfs:label</PROPERTY>
    </TARGET>

	
				<METRIC>Jaro(x.name,y.rdfs:label)</METRIC>
	
	
    <ACCEPTANCE>
        <THRESHOLD>0.10</THRESHOLD>
        <FILE>output1.nt</FILE>
       <RELATION>owl:sameAs</RELATION>
    </ACCEPTANCE>
	
    <REVIEW>
        <THRESHOLD>0.9</THRESHOLD>
        <FILE>output2.nt</FILE>
        <RELATION>owl:sameAs</RELATION>
    </REVIEW>
	thats my code... I got results that are same but there is some different results. like In resulting Datasets they interlink some links that are not same but it shows.

**Comment by Kleanthi** [comment]
Is your problem about the links you receive from running LIMES between those two endpoints? Is your problem related to the endpoints before you do the linking?

**Comment by 90arslan** [comment]
No, everything is running good but the results are not same . like i need same organization names from both datasets. In resulting datasets mostly files are not same like that.

<http://lod.openaire.eu/data/organization/corda__h2020::7907fe2bd292d02dfeab185034c3bdc0> <http://www.w3.org/1999/02/22-rdf-syntax-ns#sameAs> 
<http://cordis.rkbexplorer.com/id/organization-2d976e4505cbe9454e5e283f906f480d> .

**Comment by 90arslan** [comment]
In both links university name is half same but not completely same. how i can get exactly same result

**Comment by Kleanthi** [comment]
First of all, these are not names but URIs. They depend on KB from where you retrieve the data. 
So I don't think we can help you in changing the URIs.

Maybe your results contain indeed links with the same values in the 'name' predicate but the results of LIMES are in the form of URI1 relation URI2.

**Comment by 90arslan** [comment]
ok thank you.
